services:
  - type: web
    name: api-nest
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    preDeployCommand: npm run migration:run
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://tu-frontend-en-render.onrender.com

databases:
  - name: postgres-db
    databaseName: mydb
    user: myuser
